service: starmarketingserver

frameworkVersion: "2"

provider:
  name: aws
  lambdaHashingVersion: 20201221
  runtime: nodejs14.x  	
  memorySize: 512 # optional, in MB, default is 1024
  timeout: 30 # optional, in seconds, default is 6
  stage: dev
  region: us-east-2

functions:
  candidateSubmission:
    handler: handler.server
    memorySize: 512
    description: Submit candidate information and starts interview process.
    events:
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: true
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true

          
